#!/bin/sh
#
set -e

tmp=tmp
mkdir -p $tmp

name=$1;  shift
arch=$1;  shift

./mktest.tcl 0x0000 "$@" > $tmp/$name.s

cat $tmp/$name.s | 
/usr/local/Cellar/riscv-gnu-toolchain/master.reinstall/bin/riscv64-unknown-elf-as -march=$arch -al -o $tmp/$name.o |
awk '$1 ~ /^[0-9]+/ { $1 = sprintf("%05d", $1); $0 = $0; print }' \
> $tmp/$name.lst

cat $tmp/$name.lst |
awk '/^.*[0-9] [0-9]/ { print $1, toupper($2), substr($3, 7, 2) substr($3, 5, 2) substr($3, 3, 2) substr($3, 1, 2) }' \
> $tmp/$name.gas

cat $tmp/$name.s | sed -e s/.*#// | ../rva.tcl -march $arch - > $tmp/$name.rva

join -1 1 -2 1 $tmp/$name.gas $tmp/$name.rva > $tmp/$name.join
cat $tmp/$name.join | awk '$3 != $5 { print }' > $tmp/$name.cmp

if [ ! -s $tmp/$name.join ] ; then
    echo "No data in the join file $tmp/$name.join"
    exit 1
fi

if [ -s $tmp/$name.cmp ] ; then
    cat $tmp/$name.cmp | fldtotable line address gas rva:5 op:6- | justify
fi
