#!/bin/sh
#
set -e

name=$1;  shift
arch=$1;  shift

./mktest.tcl 0x0000 "$@" > test/$name.s

cat test/$name.s | 
/usr/local/Cellar/riscv-gnu-toolchain/master.reinstall/bin/riscv64-unknown-elf-as -march=$arch -al -o test/$name.o |
awk '$1 ~ /^[0-9]+/ { $1 = sprintf("%05d", $1); $0 = $0; print }' \
> test/$name.lst

cat test/$name.lst |
awk '/^.*[0-9] [0-9]/ { print $1, toupper($2), substr($3, 7, 2) substr($3, 5, 2) substr($3, 3, 2) substr($3, 1, 2) }' \
> test/$name.gas

cat test/$name.s | sed -e s/.*#// | ./rva.tcl -march $arch - > test/$name.rva

join -1 1 -2 1 test/$name.gas test/$name.rva > test/$name.join
cat test/$name.join | awk '$3 != $5 { print }' > test/$name.cmp

if [ -s test/$name.cmp ] ; then
    cat test/$name.cmp | fldtotable line address gas rva:5 op:6- | justify
fi
