#!/bin/sh
#
set -e

name=$1;  shift
arch=$1;  shift

./mktest.tcl 0x0000 "$@" > test/$name.s

cat test/$name.s | /usr/local/Cellar/riscv-gnu-toolchain/master.reinstall/bin/riscv64-unknown-elf-as -march=$arch -al -o test/$name.o |
awk '/^.*[0-9] [0-9]/ { print toupper($2), " ", substr($3, 7, 2) substr($3, 5, 2) substr($3, 3, 2) substr($3, 1, 2) }' \
> test/$name.gas

cat test/$name.s | sed -e s/.*#// | ./rva.tcl -march $arch - > test/$name.rva

join -1 1 -2 1 test/$name.gas test/$name.rva > test/$name.join
join -1 1 -2 1 test/$name.gas test/$name.rva | awk '$2 != $3 { print }' > test/$name.cmp

cat test/$name.cmp
